version:  build{build}

environment:
  LIBSNDFILE_LOCATION: 'c:\projects\libaudioverse\tmp'
  DEPLOYMENT_HOST: camlorn.net
  DEPLOYMENT_USERNAME: camlorn
  DEPLOYMENT_PASSWORD:
    secure: N+y3x+7kivMfuMDkYVN7CQ==
  PYPI_PASSWORD:
    secure: d2vKp79d1l2GRgzol+HVMG3GOsl0Rnq5qkZhKkLslR4=
  GIT_ACCESS_TOKEN:
    secure: FrzZP1OqCF4loe2RCRD4CQo3gRpDAJh0iE5y4/2YU9AJuXoCv138slux3gVMIMdH
  BOOST_INCLUDE_PATH: 'C:\Libraries\boost_1_59_0'
  matrix:
    - ARCHITECTURE: x86
      LIBSNDFILE_URL: http://camlorn.net/appveyor/libsndfile32
      NUMPY_URL: http://camlorn.net/appveyor/numpy-1.10.1+mkl-cp35-none-win32.whl
      SCIPY_URL: http://camlorn.net/appveyor/scipy-0.16.1-cp35-none-win32.whl
      PYTHON_COMMAND: 'c:\python35\python'
      BOOST_LIB_PATH: 'c:\libraries\boost_1_59_0\lib32-msvc-14.0'
    - ARCHITECTURE: amd64
      LIBSNDFILE_URL: http://camlorn.net/appveyor/libsndfile64
      NUMPY_URL: http://camlorn.net/appveyor/numpy-1.10.4+mkl-cp35-cp35m-win_amd64.whl
      SCIPY_URL: http://camlorn.net/appveyor/scipy-0.17.1-cp35-cp35m-win_amd64.whl
      PYTHON_COMMAND: 'C:\Python35-x64\python'
      BOOST_LIB_PATH: 'c:\libraries\boost_1_59_0\lib64-msvc-14.0'

matrix:
  fast_finish: true

init:
  - git config --global core.autocrlf true
  - git config --global credential.helper store
  - 'git config --global user.name "Austin Hicks"'
  - git config --global user.email camlorn@camlorn.net

clone_folder: c:\projects\libaudioverse

platform:
  - x86
configuration:
  - Release


install:
  #Store our git credentials. This comes from Appveyor docs.
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GIT_ACCESS_TOKEN):x-oauth-basic@github.com`n"
  - '%PYTHON_COMMAND% -m pip install -U pip setuptools'
  #Bring in jinja2, pycparser, etc. Paramiko needs pycrypto.
  - '%PYTHON_COMMAND% -m pip install jinja2 pycparser pyyaml wheel twine pypandoc sphinx sphinx_rtd_theme %NUMPY_URL% %SCIPY_URL%'
  #This next one gets a bit interesting: we need to download and silently install libsndfile.
  - mkdir tmp
  - cd tmp
  - echo Downloading Libsndfile.
  - mkdir bin
  - cd bin
  - appveyor DownloadFile %LIBSNDFILE_URL%/libsndfile-1.dll
  - cd ..
  - mkdir include
  - cd include
  - appveyor DownloadFile %LIBSNDFILE_URL%/sndfile.h
  - cd ..
  - mkdir lib
  - cd lib
  - appveyor DownloadFile %LIBSNDFILE_URL%/libsndfile-1.lib
  - cd ..
  - cd ..
  - set path=c:\projects\libaudioverse\tmp;%path%
  - gem install asciidoctor


build_script:
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCHITECTURE%'
  #Do this heere so we can be absolutely sure it's set right:
  - 'set include=%BOOST_INCLUDE_PATH%;%include%'
  - 'set lib=%BOOST_LIB_PATH%;%lib%'
  - mkdir build
  - cd build
  #Turn off devmode to make docs be part of all.
  - 'cmake .. -G "NMake Makefiles" -DLIBAUDIOVERSE_DEVMODE:BOOL=OFF -DLIBSNDFILE_LOCATION:STRING="c:/projects/libaudioverse/tmp"'
  - nmake
  #Go back, so that after_build works.
  - cd ..

after_build:
  - echo uploading docs
  - '%PYTHON_COMMAND% scripts\push_docs.py'

artifacts:
  - path: 'build\artifacts\*'

#GitHub deployment.
deploy:
  provider: GitHub
  description: Libaudioverse release.
  auth_token:
    secure: FrzZP1OqCF4loe2RCRD4CQo3gRpDAJh0iE5y4/2YU9AJuXoCv138slux3gVMIMdH
  on:
    appveyor_repo_tag: true
